### ISSUE TITLE
Handle when no CAS segments are present in reduce function

### ISSUE THREAD

**Issue by zavoraad** [databricks-industry-solutions/x12-edi-parser#25]

**Comment by zavoraad** [comment]
With no CAS segment, error is

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aaron.zavora/python/x12-edi-parser/databricksx12/hls/healthcare.py", line 22, in from_edi
    return self.flatmap(self.flatmap([self.from_functional_group(y) for y in edi.functional_segments()]))
  File "/Users/aaron.zavora/python/x12-edi-parser/databricksx12/hls/healthcare.py", line 22, in <listcomp>
    return self.flatmap(self.flatmap([self.from_functional_group(y) for y in edi.functional_segments()]))
  File "/Users/aaron.zavora/python/x12-edi-parser/databricksx12/hls/healthcare.py", line 28, in from_functional_group
    return [self.from_transaction(x) for x in fg.transaction_segments()]
  File "/Users/aaron.zavora/python/x12-edi-parser/databricksx12/hls/healthcare.py", line 28, in <listcomp>
    return [self.from_transaction(x) for x in fg.transaction_segments()]
  File "/Users/aaron.zavora/python/x12-edi-parser/databricksx12/hls/healthcare.py", line 35, in from_transaction
    return ClaimBuilder(self.mapping.get(trnx.transaction_type),
  File "/Users/aaron.zavora/python/x12-edi-parser/databricksx12/hls/claim.py", line 114, in build
    return [
  File "/Users/aaron.zavora/python/x12-edi-parser/databricksx12/hls/claim.py", line 115, in <listcomp>
    self.build_remittance(seg, i) for i, seg in self.segments_by_name_index("CLP")
  File "/Users/aaron.zavora/python/x12-edi-parser/databricksx12/hls/claim.py", line 50, in build_remittance
    return self.trnx_cls(trx_header_loop = self.data[0:self.index_of_segment(self.data, "N1")]
  File "/Users/aaron.zavora/python/x12-edi-parser/databricksx12/hls/claim.py", line 333, in __init__
    self.build()
  File "/Users/aaron.zavora/python/x12-edi-parser/databricksx12/hls/claim.py", line 339, in build
    self.clm_info = self.populate_claim_loop()
  File "/Users/aaron.zavora/python/x12-edi-parser/databricksx12/hls/claim.py", line 408, in populate_claim_loop
    'service_adjustments': functools.reduce(lambda x,y: x+y,
TypeError: reduce() of empty sequence with no initial value
```
